import { prisma } from "../lib/prisma.js";
import bcrypt from "bcryptjs";

const DEV_USERS = [
  { email: "dev1@example.com", password: "DevPassword123!", name: "Dev One" },
  { email: "dev2@example.com", password: "DevPassword123!", name: "Dev Two" },
];

const cards = [
{ name: "Gold 1",
rarity: "",
description: "...",
imageUrl: "/cards/....png",
atk: 100,
wis: 4,
def: 52,
spd: 112},
{ name: "Gold 2",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 92,
wis: 8,
def: 44,
spd: 128},
{ name: "Gold 3",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 84,
wis: 12,
def: 36,
spd: 144},
{ name: "Gold 4",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 76,
wis: 16,
def: 28,
spd: 160},
{ name: "Gold 5",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 68,
wis: 20,
def: 20,
spd: 176},
{ name: "Gold 6",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 60,
wis: 24,
def: 12,
spd: 192},
{ name: "Gold 7",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 52,
wis: 28,
def: 100,
spd: 16},
{ name: "Gold 8",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 44,
wis: 32,
def: 92,
spd: 32},


{ name: "Silver 1",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 100,
wis: 6,
def: 44,
spd: 136},
{ name: "Silver 2",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 92,
wis: 10,
def: 36,
spd: 152},
{ name: "Silver 3",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 84,
wis: 14,
def: 28,
spd: 168},
{ name: "Silver 4",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 76,
wis: 18,
def: 20,
spd: 184},
{ name: "Silver 5",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 68,
wis: 22,
def: 12,
spd: 200},
{ name: "Silver 6",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 60,
wis: 26,
def: 100,
spd: 24},
{ name: "Silver 7",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 52,
wis: 30,
def: 92,
spd: 40},

{ name: "Amethyst 1",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 96,
wis: 6,
def: 48,
spd: 120},
{ name: "Amethyst 2",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 88,
wis: 10,
def: 40,
spd: 136},
{ name: "Amethyst 3",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 80,
wis: 14,
def: 32,
spd: 152},
{ name: "Amethyst 4",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 72,
wis: 18,
def: 24,
spd: 168},
{ name: "Amethyst 5",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 64,
wis: 22,
def: 16,
spd: 184},
{ name: "Amethyst 6",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 56,
wis: 26,
def: 8,
spd: 200},
{ name: "Amethyst 7",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 48,
wis: 30,
def: 96,
spd: 24},
{ name: "Amethyst ",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 40,
wis: 34,
def: 88,
spd: 40},

{ name: "Platinum 1",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 96,
wis: 8,
def: 40,
spd: 144},
{ name: "Platinum 2",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 88,
wis: 12,
def: 32,
spd: 160},
{ name: "Platinum 3",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 80,
wis: 16,
def: 24,
spd: 176},
{ name: "Platinum 4",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 72,
wis: 20,
def: 16,
spd: 192},
{ name: "Platinum 5",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 64,
wis: 24,
def: 8,
spd: 16},
{ name: "Platinum 6",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 56,
wis: 28,
def: 96,
spd: 32},
{ name: "Platinum 7",
rarity: "...",
description: "...",
imageUrl: "/cards/....png",
atk: 48,
wis: 32,
def: 88,
spd: 48},
];

async function seedDevUsers() {
  if (process.env.NODE_ENV === "production") return;

  for (const user of DEV_USERS) {
    const passwordHash = await bcrypt.hash(user.password, 10);
    await prisma.user.upsert({
      where: { email: user.email },
      update: {}, // leave it alone if it already exists
      create: {
        email: user.email,
        passwordHash,
        name: user.name,
      },
    });
  }

  console.log("Dev users ready:");
  for (const user of DEV_USERS) {
    console.log(`  ${user.email} / ${user.password}`);
  }
}

async function seedCards() {
  for (const card of cards) {
    await prisma.card.upsert({
      where: { name: card.name },
      update: card,
      create: card,
    });
  }
  console.log(`Seeded ${cards.length} cards.`);
}

async function main() {
  await seedDevUsers();
  await seedCards();
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
